### PR TITLE
Promises

### PR DESCRIPTION
**Pull request by kylemac**
any interest into converting the library to use promises? 
- uses bluebird
- fully tested

i've also upped the code coverage with some additional tests 
screen shot 2015-05-13 at 1 09 56 pm

### CODE REVIEW

**Comment by kylemac** [comment]
adding documentation coverage now too. almost forgot

**Comment by jonkemp** [comment]
Sorry for ignoring this for so long. I am interested in this. Can you please fix the merge conflicts? I'll take another look. Thanks!

**Comment by jonkemp** [comment]
Er, remove/fix that last commit, squash your commits and then I can resolve the conflicts if you want. Thanks.

**Comment by kylemac** [comment]
@jonkemp yeah - that merge didn't go too well ha. working on fixing that up - just in the middle of something

**Pull request closed without merging**
