### PR TITLE
Chore: Bump cheerio from 0.22.0 to 1.0.0-rc.10

### PR DESCRIPTION
**Pull request by Yaminyam**
#111 There was an nth-check security issue in cheerio > css-select > nth-check dependency, so cheerio version was updated

### CODE REVIEW

**Comment by derekbwarren** [comment]
Is it possible for this PR to get merged to resolve this issue?

**Comment by jonkemp** [comment]
I wonder why the tests didn't run. I would need to verify that first.

**Comment by Yaminyam** [comment]
> I wonder why the tests didn't run. I would need to verify that first.

Merge from forked repositories does not have permission for action

**Comment by jonkemp** [comment]
Tests are failing.

**Comment by jonkemp** [comment]
Tests are failing.

**Comment by pleymor** [comment]
All tests were successful when I launched npm run test.
Which one did u see failing please?

**Comment by jonkemp** [comment]
@pleymor this is not your pr but I did leave feedback on yours too. Can you address that?

**Pull request closed without merging**
