### PR TITLE
Adding ability to compile with XML

### PR DESCRIPTION
**Pull request by sgarbesi**
https://github.com/jonkemp/gulp-inline-css/issues/28

https://github.com/cheeriojs/cheerio/issues/378

### CODE REVIEW

**Comment by jonkemp** [comment]
Looks interesting. Please include a test case.

**Comment by sgarbesi** [comment]
@jonkemp I would if I had time. For now I'm just resorting to using my PR to build the templates.

**Comment by jonkemp** [comment]
Closing.

**Comment by albell** [comment]
+1 Please consider merging. My use case (and the typical one, I think) is email. Inlining styles is mostly needed for older email clients, some of which only support XML.

**Pull request closed without merging**
