### PR TITLE
Add option to apply height attributes to elements

### PR DESCRIPTION
**Pull request by infiniteimprobability**
I spun off option.applyWidthAttributes into option.applyHeightAttributes. This is useful for maintaining layout in HTML emails before images have been loaded.

### CODE REVIEW

**Comment by jonkemp** [comment]
You mean `options.applyHeightAttributes`?

**Comment by infiniteimprobability** [comment]
@jonkemp Updated, thanks!

**Comment by infiniteimprobability** [comment]
Updated to address some conflicts with #7

**Comment by jonkemp** [comment]
I'm not sure how relevant this is. Setting the width on td's for html is pretty standard. I don't think the same thing applies to setting the height.

**Comment by infiniteimprobability** [comment]
The use case seems very similar to turning on width HTML attributes. I use height attributes on TABLE/TD all of the time when doing fixed-dimension layouts. If I'm doing a vertically-fluid layout I would probably not set CSS height properties on most table/td elements anyway, so there would no effect on their HTML attributes.

**Comment by jonkemp** [comment]
I don't think I'm going to accept this at this time. My suggestion would be to make a feature request in the issues and see how many other users want this.

**Pull request closed without merging**
