### PR TITLE
Add !important atribute

### PR DESCRIPTION
**Pull request by csscoderRU**
Important attibute is very necessary for E-mail develop (for exapmple Outlook web version on links)

### CODE REVIEW

**Comment by csscoderRU** [comment]
Sorry, it's work only gulp-inline-css

**Comment by jonkemp** [comment]
Mosts tests are failing now.

**Comment by csscoderRU** [comment]
Hi, I'm update pull

**Comment by jonkemp** [comment]
Ok, do a pull and run `gulp lint` and fix lint errors please.

**Comment by jonkemp** [comment]
This is a fix for https://github.com/jonkemp/gulp-inline-css/issues/17.

**Comment by csscoderRU** [comment]
Hi, Jonathan. I fix jshint error (only my part)

**Comment by jonkemp** [comment]
Looks good. Please squash your commits and I'll accept. Thanks!

**Comment by csscoderRU** [comment]
Hi, Jonathan. Please check ) Maybe I wrong. I can't squash my commits (correct)

**Comment by jonkemp** [comment]
No, I don't think I can accept it as is now. I'm seeing my own changes in there which have already been committed. Squashing should have combined all of your changes into one commit. Here's more on how to do that.

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

If you can do that, great! If not, you may have to close this one and open a new pull request. Thanks.

**Comment by csscoderRU** [comment]
Jonathan, hello! Maybe now is correct)

**Comment by jonkemp** [comment]
This was merged. Somehow this did not get closed. Closing now.

Fixes jonkemp/gulp-inline-css#17.

**Pull request closed without merging**
